runtime: python39

instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2

entrypoint: gunicorn -b :8080 app/app:app

handlers:
- url: /static
  static_dir: app/static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

includes:
- env.yaml
