runtime: python39

instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: /.*
  script: auto

includes:
- env.yaml
